server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: cowork-config
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/auth/
            - classpath:/collab/
            - classpath:/doc/
            - classpath:/gateway/
            - classpath:/group/
            - classpath:/user/
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
