server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://cowork_doc:123456@db-doc:27017/cowork_doc?authSource=admin&authMechanism=SCRAM-SHA-1
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: cowork-kafka:9092
      bindings:
        input:
          binder: kafka
          destination: crdt
