apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: cowork
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-redis
          image: registry.k8s.io/busybox:1.24
          command: [ 'sh', '-c', 'until nslookup redis-service; do echo waiting for redis-service; sleep 2; done;' ]
        - name: wait-user
          image: registry.k8s.io/busybox:1.24
          command: [ 'sh', '-c', 'until nslookup user-service; do echo waiting for user-service; sleep 2; done;' ]
      containers:
        - name: auth
          image: cowork-auth:latest
          imagePullPolicy: Never
          env:
            - name: PROFILE
              value: "k8s"
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: redis-url
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: cowork
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      name: http

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
  namespace: cowork
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 70
          type: AverageValue