apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: cowork
data:
  SECRET: cmVkaXMxMjM0NTY=

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: cowork
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    timeout 10
    dir "/data"
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    supervised no
    always-show-logo yes
    loglevel notice
  init.sh: |
    [[ $(hostname) == "redis-0" ]] || exit 0
    for i in $(seq 0 2); do
      until sh -c "nslookup \$(hostname -f | sed -e 's/[0-9]\./$i./')" &>/dev/null; do
        echo "waiting for redis-$i"
        sleep 1
      done
    done
    NODES=$(sh -c "for i in \$(seq 0 2); do nslookup \$(hostname -f | sed -e \"s/[0-9]\./\$i./\") | grep -oE \"\b([0-9]{1,3}\.){3}[0-9]{1,3}\b\" | tail -1 | tr '\n' ' ' | sed 's/ /:6379 /'; done")
    echo "cluster nodes $NODES"
    echo "yes" | redis-cli -a $SECRET --cluster create $NODES
  start.sh: |
    sh /etc/redis/init.sh &
    redis-server /etc/redis/redis.conf --requirepass $SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cowork
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: cowork
spec:
  serviceName: redis-service
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.3-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - /etc/redis/start.sh
          envFrom:
            - secretRef:
                name: redis-secret
          resources:
            limits:
              memory: 128Mi
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379
              name: cluster
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        namespace: cowork
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 128Mi