// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initialize() (runner, func(), error) {
	mainConfig := newConfig()
	echo := newEngine(mainConfig)
	universalClient, cleanup, err := newRedisClient(mainConfig)
	if err != nil {
		return nil, nil, err
	}
	mainTokenService := newTokenService(mainConfig, universalClient)
	client, cleanup2 := newUserClient(mainConfig)
	mainRouter := newRouter(mainTokenService, client)
	mainRunner := newRunner(mainConfig, echo, mainRouter)
	return mainRunner, func() {
		cleanup2()
		cleanup()
	}, nil
}
