server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://dev:123456@localhost:27017/dev?authSource=admin

nats:
  spring:
    server: nats://localhost:4222

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.transaction.interceptor: TRACE

grpc:
  server:
    port: 9094