// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initialize() (runner, func(), error) {
	mainConfig := newConfig()
	engine := newEngine(mainConfig)
	client, cleanup := newDocClient(mainConfig)
	conn, cleanup2, err := newNats(mainConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clientClient, cleanup3 := newUserClient(mainConfig)
	universalClient, cleanup4, err := newRedisClient(mainConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	hub, cleanup5 := newHub(client, conn, clientClient, universalClient)
	mainRunner := newRunner(mainConfig, engine, hub)
	return mainRunner, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
