// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/shiroyk/cowork/user/router"
	"github.com/shiroyk/cowork/user/service"
)

// Injectors from wire.go:

func initialize() (runner, error) {
	mainConfig := newConfig()
	engine := newEngine(mainConfig)
	db, err := newDB(mainConfig)
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(db)
	routerRouter := router.NewRouter(userService)
	userServiceServer := service.NewGrpcService(db)
	mainRunner := newRunner(mainConfig, engine, routerRouter, userServiceServer)
	return mainRunner, nil
}

// wire.go:

var serviceSets = wire.NewSet(service.NewUserService, service.NewGrpcService)
