apiVersion: v1
kind: Namespace
metadata:
  name: cowork

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: cowork
data:
  JWT_SECRET: Y293b3JrLWp3dC1zZWNyZXQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: redis-url
  namespace: cowork
data:
  REDIS_URL: cmVkaXM6Ly9kZWZhdWx0OnJlZGlzMTIzNDU2QHJlZGlzLXNlcnZpY2U6NjM3OQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: nats-url
  namespace: cowork
data:
  NATS_URL: bmF0czovL25hdHMxMjM0NUBuYXRzLXNlcnZpY2U6NDIyMg==

---

apiVersion: v1
kind: Secret
metadata:
  name: user-db-url
  namespace: cowork
data:
  USER_DB_URL: dXNlcjp1c2VyMTIzNDU2QHRjcChkYi11c2VyLXNlcnZpY2U6MzMwNikvY293b3JrX3VzZXI/Y2hhcnNldD11dGY4bWI0JnBhcnNlVGltZT1UcnVlJmxvYz1Mb2NhbA==

---

apiVersion: v1
kind: Secret
metadata:
  name: doc-db-url
  namespace: cowork
data:
  DOC_DB_URL: bW9uZ29kYjovL2RvYzpkb2MxMjM0NTZAZGItZG9jLXNlcnZpY2U6MjcwMTcvY293b3JrX2RvYz9hdXRoU291cmNlPWFkbWluJnJlcGxpY2FTZXQ9cnMwJnJlYWRQcmVmZXJlbmNlPXByaW1hcnk=

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: auth-config
  namespace: cowork
data:
  config.yaml: |-
    redis: ${REDIS_URL}
    grpc-user: ${USER_SERVICE_SERVICE_HOST}:${USER_SERVICE_SERVICE_PORT_GRPC}
    jwt-secret: ${JWT_SECRET}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: user-config
  namespace: cowork
data:
  config.yaml: |-
    mysql: ${USER_DB_URL}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: doc-config
  namespace: cowork
data:
  config.yaml: |-
    mongodb: ${DOC_DB_URL}
    nats: ${NATS_URL}
    stream:
      wait: 5
      flush_size: 16

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: collab-config
  namespace: cowork
data:
  config.yaml: |-
    redis: ${REDIS_URL}
    nats: ${NATS_URL}
    grpc-doc: ${DOC_SERVICE_SERVICE_HOST}:${DOC_SERVICE_SERVICE_PORT_GRPC}
    grpc-user: ${USER_SERVICE_SERVICE_HOST}:${USER_SERVICE_SERVICE_PORT_GRPC}

---

apiVersion: v1
data:
  server-snippet: |
    error_page 401 /401.json;
    location = /401.json {
        return 401 '{"error":"Unauthorized"}';
    }
    error_page 500 /500.json;
    location = /500.json {
        return 500 '{"error":"Internal Server Error"}';
    }
    error_page 503 /503.json;
    location = /503.json {
        return 503 '{"error":"Service Unavailable"}';
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.8.1
  name: ingress-nginx-controller
  namespace: ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-auth
  namespace: cowork
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: http://app.cowork.local
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api$1$2
    nginx.ingress.kubernetes.io/auth-url: http://auth-service.cowork.svc.cluster.local:8080/auth
    nginx.ingress.kubernetes.io/auth-response-headers: X-User-Id
spec:
  ingressClassName: "nginx"
  rules:
    - host: api.cowork.local
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 8080
          - path: /users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 8080
          - path: /doc(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: doc-service
                port:
                  number: 8080
          - path: /collab(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: collab-service
                port:
                  number: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-public
  namespace: cowork
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: http://app.cowork.local
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  ingressClassName: "nginx"
  rules:
    - host: api.cowork.local
      http:
        paths:
          - path: /auth/(sign_in|sign_up|refresh)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: cowork
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: "nginx"
  rules:
    - host: app.cowork.local
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 80