apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: cowork
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-redis
          image: alpine:3.16
          command:
            - sh
            - -c
            - |
              until nc -vz redis-service 6379; do echo waiting for redis-service; sleep 2; done;
              until nc -vz user-service 9090; do echo waiting for user-service; sleep 2; done;
      containers:
        - name: auth
          image: cowork-auth:latest
          imagePullPolicy: Never
          env:
            - name: PROFILE
              value: "k8s"
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: redis-url
          volumeMounts:
            - name: app-config
              mountPath: /etc/app/
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: app-config
          configMap:
            name: auth-config
---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: cowork
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      name: http

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
  namespace: cowork
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 70
          type: AverageValue